import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ThemeContext, ThemeProvider } from "@/context/ThemeContext";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "simple projet for question language",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="pt-BR">
        <ThemeContext.Consumer>
          {({ theme }) => (
            <body className={[inter.className, theme === 'dark' ? 'dark' : ''].join(',')}>{children}</body>
          )}
        </ThemeContext.Consumer>
      </html>
    </ThemeProvider>
  );
}
